# Generated by Django 4.2.9 on 2024-02-07 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='subcategory',
        #     name='sorting_order',
        # ),
    ]
