# Generated by Django 4.2.9 on 2024-02-07 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_subcategory_sorting_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='sorting_order',
        ),
    ]
