# Generated by Django 4.2.9 on 2024-02-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_remove_subcategory_sorting_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, default='', upload_to='category_images/'),
        ),
    ]
