# Generated by Django 4.2.9 on 2024-04-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_category_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
