# Generated by Django 4.2.9 on 2024-04-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_category_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='discount_percentage',
            field=models.IntegerField(default=10),
        ),
    ]
