# Generated by Django 4.2.9 on 2024-02-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_alter_product_image_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
