# Generated by Django 4.2.9 on 2024-02-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_rename_category_id_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_price',
        ),
    ]
