# Generated by Django 4.2.9 on 2024-02-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0006_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_price',
        ),
    ]
