# Generated by Django 4.2.9 on 2024-02-22 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0007_remove_product_images_remove_product_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atrribute_name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='attribute_values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.CharField(max_length=40, unique=True)),
                ('attr_is_active', models.BooleanField(default=True)),
                ('attribute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Product_varient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(blank=True, max_length=200)),
                ('stock', models.IntegerField(default=0)),
                ('sku_id', models.CharField(default='', max_length=30, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('thumbnail_image', models.ImageField(blank=True, upload_to='product/product_thumbnail')),
                ('product_variant_slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('varient_is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.ManyToManyField(max_length=100, related_name='attributes', to='product_management.attribute_values')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_var', to='product_management.product')),
            ],
        ),
    ]
