# Generated by Django 4.2.9 on 2024-02-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0009_product_images_alter_product_image_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_varient',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product_varient',
            name='sku_id',
        ),
    ]
