# Generated by Django 4.2.9 on 2024-02-28 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0010_remove_product_varient_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute_values',
            name='attribute_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribute_value_set', to='product_management.attribute'),
        ),
    ]
