# Generated by Django 4.2.9 on 2024-03-03 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0011_alter_attribute_values_attribute_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_varient',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='product_varient',
            name='product_name',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='Brand_name',
            new_name='brand_name',
        ),
        migrations.AlterField(
            model_name='product_image',
            name='image',
            field=models.ImageField(upload_to='product_variant_image/'),
        ),
        migrations.RenameModel(
            old_name='attribute_values',
            new_name='Attribute_value',
        ),
        migrations.CreateModel(
            name='Product_variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(blank=True, max_length=200)),
                ('stock', models.IntegerField(default=0)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('thumbnail_image', models.ImageField(blank=True, upload_to='product/product_thumbnail')),
                ('variant_slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('variant_is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ManyToManyField(max_length=100, related_name='attribute', to='product_management.attribute_value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_var', to='product_management.product')),
            ],
        ),
        migrations.AlterField(
            model_name='product_image',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_image', to='product_management.product_variant'),
        ),
    ]
