# Generated by Django 4.2.9 on 2024-03-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0012_remove_product_varient_attributes_and_more'),
        ('cart', '0002_alter_cartitem_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_varient',
        ),
    ]
