# Generated by Django 4.2.9 on 2024-03-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='photos/user_images'),
        ),
    ]
