# Generated by Django 4.2.9 on 2024-03-16 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_address_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country_region',
        ),
    ]
