# Generated by Django 4.2.9 on 2024-03-14 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_address_order_country_region_order_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='country_region',
        ),
    ]
