# Generated by Django 4.2.9 on 2024-03-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_country_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product_id',
            new_name='variant_id',
        ),
    ]
