# Generated by Django 4.2.9 on 2024-03-15 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_product_id_orderproduct_variant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='grand_totol',
            new_name='total',
        ),
    ]
