# Generated by Django 4.2.9 on 2024-03-31 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_payment_payment_order_id_payment_payment_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
    ]
